### ISSUE TITLE
Pipeline failure at Package stage: "This build image requires selecting at least one runtime version."

### ISSUE THREAD

**Issue by mmunem** [awslabs/aws-service-catalog-factory#126]
Using the following product: 

https://github.com/awslabs/aws-service-catalog-products/tree/master/multi-account-aws-securityhub/securityhub-spoke/v1

Build logs

`
[Container] 2020/02/03 10:56:46 Waiting for agent ping
[Container] 2020/02/03 10:56:48 Waiting for DOWNLOAD_SOURCE
[Container] 2020/02/03 10:56:48 Phase is DOWNLOAD_SOURCE
[Container] 2020/02/03 10:56:48 CODEBUILD_SRC_DIR=/codebuild/output/src253253372/src
[Container] 2020/02/03 10:56:48 YAML location is /codebuild/readonly/buildspec.yml
[Container] 2020/02/03 10:56:48 Processing environment variables
[Container] 2020/02/03 10:56:48 Moving to directory /codebuild/output/src253253372/src
[Container] 2020/02/03 10:56:48 Phase complete: DOWNLOAD_SOURCE State: FAILED
[Container] 2020/02/03 10:56:48 Phase context status code: YAML_FILE_ERROR Message: This build image requires selecting at least one runtime version.
`

**Comment by mckayjuk** [comment]
I had similar in different products but at the same stage.

Looking at the issue, it appears we need to specify the run time version in the 'PackageProject' CodeBuild job. 

https://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html#troubleshooting-build-must-specify-runtime

This seems to relate to the 'product-cloudformation.j2' file in the SC-F codebase.

I have made a local change in my deployment account as below which allowed the pipeline to run through successfully:

````
version: 0.2
phases:

# Added the install section to test fix
  install:
    runtime-versions:
        python: 3.8
# End of fix
  build:
    commands:
      - pip install -r requirements.txt -t src
    
      - aws cloudformation package --template $(pwd)/product.template.yaml --s3-bucket sc-factory-artifacts-${ACCOUNT_ID}-eu-west-1 --s3-prefix ${STACK_NAME} --output-template-file product.template-eu-west-1.yaml
    
      - aws cloudformation package --template $(pwd)/product.template.yaml --s3-bucket sc-factory-artifacts-${ACCOUNT_ID}-eu-west-2 --s3-prefix ${STACK_NAME} --output-template-file product.template-eu-west-2.yaml
    
artifacts:
  files:
    - '*'
    - '**/*'
````

I'll make an update and raise a pull request
