### ISSUE TITLE
Failure to launch products in other regions (S3 Bucket Reference Issue)

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-factory#167]
We have SCF deployed in eu-west-2, but configured to deploy products to both eu-west-2 & us-east-1.

We've recently noticed that we're unable to deploy / update products in us-east-1 where the product refers to artefacts uploaded to S3 as part of the `aws cloudformaiton package` command that the `Package` stage executes (e.g. Lambdas, Nested Stacks etc).

The error we get looks something like below (This was when referring to a Nested Stack template):

```
2020-12-04 11:27:39 UTC+0000 | ConfigLayerStack | CREATE_FAILED | S3 error: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
-- | -- | -- | --
```

This products works fine in eu-west-2.

On further investigation, we inspected the template file in the product for both regions and think we've spotted the issue. They are the same, and in the above example, the template looks like this (Snippet for simplicity):

```yaml
Resources:
  ConfigLayerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/sc-factory-artifacts-12345678910-us-east-1/jordan-test-base-jordan-base-layer-master/f19dbf5db0610f36cc8e1d42ab1b8c1e.template
```

The issue seems to be in the first part of the URL. It explicitly refers to `https://s3.**eu-west-2**.amazonaws.com/`, which explains why this product works in eu-west-2, but fails in any other region, as the bucket for each region belongs to that specific region (e.g. CloudFormation is trying to look for `sc-factory-artifacts-12345678910-us-east-1` in eu-west-2, not us-east-1).

I've attempted the below fix in the Package command which solves the issue for this one product, but looks like this might need a fix in Factory.

Instead of
```bash
aws cloudformation package --template $(pwd)/product.template.yaml --s3-bucket sc-factory-artifacts-${ACCOUNT_ID}-us-east-1 --s3-prefix ${STACK_NAME} --output-template-file product.template-us-east-1.yaml
```

Use
```bash
aws cloudformation package --region us-east-1 --template $(pwd)/product.template.yaml --s3-bucket sc-factory-artifacts-${ACCOUNT_ID}-us-east-1 --s3-prefix ${STACK_NAME} --output-template-file product.template-us-east-1.yaml
```

After which, the eu-west-2 template remains the same, but the us-east-1 now looks like below, and successfully deploys

```yaml
Resources:
  ConfigLayerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/sc-factory-artifacts-12345678910-us-east-1/jordan-test-base-jordan-base-layer-master/4859abfac71a654da061e0e0e28acef6.template
```

I've confirmed this behaviour in the latest release (`0.48.1`).
