### ISSUE TITLE
S3 Combined Pipelines

### ISSUE THREAD

**Issue by Mladen-Trampic-SRB-1989** [awslabs/aws-service-catalog-factory#194]
Hi @eamonnfaherty , hope all good ! 

Quick Q :  

From Docs : https://aws-service-catalog-factory.readthedocs.io/en/latest/factory/building_your_pipelines.html#reducing-the-number-of-pipelines

```yaml
Products:
  - Description: iam-assume-roles-spoke product
    Distributor: central-it-team
    Name: aws-iam-assume-roles-spoke
    Owner: central-it@customer.com
    SupportDescription: Contact us on Chime for help
    SupportEmail: central-it-team@customer.com
    SupportUrl: https://wiki.customer.com/central-it-team/self-service/account-iam
    PipelineMode: combined
    Portfolios:
      - combined 
```

Digging around and looking code, I came to conclusion something is not supported there.

https://github.com/awslabs/aws-service-catalog-factory/blob/050a3e43ac9fa0997f43311cf3a62026961ca9ba/servicecatalog_factory/templates/product-combined-cloudformation.j2#L84-L98

From code i understand that all versions will be pointing to same S3 object. 

To make it most simple: 
- Combined  Pipelines with S3 provider are not supported ?
