### ISSUE TITLE
Creating of stacks with S3 as source fails.

### ISSUE THREAD

**Issue by Lazarevsky** [awslabs/aws-service-catalog-factory#201]
stacks/baseline-optional.yaml:

```
Schema: factory-2019-04-01
Stacks:
  - Name: "ccoe-inet-in-controls"
    Versions:
      - Name: "v1"
        Source:
          Provider: "S3"
          Configuration:
            BucketName: "ccoe-landing-zone-service-catalog-tools-rbi-test"
            S3ObjectKey: "ccoe-inet-in-controls/v1/product.zip"
  - Name: "ccoe-inet-in-pa10-orchestrator"
    Versions:
      - Name: "v1"
        Source:
          Provider: "S3"
          Configuration:
            BucketName: "ccoe-landing-zone-service-catalog-tools-rbi-test"
            S3ObjectKey: "ccoe-inet-in-pa10-orchestrator/v1/product.zip"
  - Name: "ccoe-inet-in-pa10-orchestrator-event-bridge-ssm-parameter"
    Versions:
      - Name: "v1"
        Source:
          Provider: "S3"
          Configuration:
            BucketName: "ccoe-landing-zone-service-catalog-tools-rbi-test"
            S3ObjectKey: "ccoe-inet-in-pa10-orchestrator-event-bridge-ssm-parameter/v1/product.zip"
```

Factory Codebuild Stage output (relevant lines):

```
ERROR: [pid 341] Worker Worker(salt=329767164, workers=10, host=1e390178ec42, username=root, pid=288) failed    CreateGenericVersionPipelineTask(category=stack, name=ccoe-inet-in-controls, version=v1, source={"Provider": "S3", "Configuration": {"BucketName": "ccoe-landing-zone-service-catalog-tools-rbi-test", "S3ObjectKey": "ccoe-inet-in-controls/v1/product.zip"}}, options={}, stages={})
--


botocore.exceptions.ClientError:
 An error occurred (ValidationError) when calling the CreateStack 
operation: 
[/Resources/Pipeline/Type/Stages/0/Actions/0/Configuration/PollForSourceChanges]
 'null' values are not allowed in templates
```

The error happens in the stack template builder:
https://github.com/awslabs/aws-service-catalog-factory/blob/86d5528997d1225f7446f879806f8798052c0135/servicecatalog_factory/template_builder/builders.py#L135

**Comment by Lazarevsky** [comment]
Setting PollSourceForChanges: True under Configuration didn't do the trick either:

stacks/baseline-mandatory.yaml

```
Schema: factory-2019-04-01
Stacks:
  - Name: "ccoe-inet-in-controls"
    Versions:
      - Name: "v1"
        Source:
          Provider: "S3"
          Configuration:
            BucketName: "ccoe-landing-zone-service-catalog-tools-rbi-test"
            S3ObjectKey: "ccoe-inet-in-controls/v1/product.zip"
            PollForSourceChanges: True
  - Name: "ccoe-inet-in-pa10-orchestrator"
    Versions:
      - Name: "v1"
        Source:
          Provider: "S3"
          Configuration:
            BucketName: "ccoe-landing-zone-service-catalog-tools-rbi-test"
            S3ObjectKey: "ccoe-inet-in-pa10-orchestrator/v1/product.zip"
            PollForSourceChanges: True
  - Name: "ccoe-inet-in-pa10-orchestrator-event-bridge-ssm-parameter"
    Versions:
      - Name: "v1"
        Source:
          Provider: "S3"
          Configuration:
            BucketName: "ccoe-landing-zone-service-catalog-tools-rbi-test"
            S3ObjectKey: "ccoe-inet-in-pa10-orchestrator-event-bridge-ssm-parameter/v1/product.zip"
            PollForSourceChanges: True
```

Codebuild output:
CreateGenericVersionPipelineTask failed
--


<html><body>
<span><span><span>

 
--


</span></span></span><span><span><span>botocore.exceptions.ClientError:
 An error occurred (ValidationError) when calling the CreateStack 
operation: 
[/Resources/Pipeline/Type/Stages/0/Actions/0/Configuration/S3Bucket] 
'null' values are not allowed in templates</span></span></span>
</body>
</html>
