### ISSUE TITLE
Setting Stacks to terminated does not remove existing CodePipeline pipelines

### ISSUE THREAD

**Issue by richardmilnerwatts** [awslabs/aws-service-catalog-factory#207]
**Observed Behaviour:**

I marked two S3 sourced Stacks as terminated in my Factory configuration and pushed the change. The Factory pipeline ran successfully, but did not delete:

- The CodePipeline pipelines
- Any assets from my sc-puppet-stacks-repository-<AWSAccount> bucket

**Expected Behaviour:**

I would expect that marking a stack as terminated would clean up and remove the CodePipeline pipelines which Factory has created.

I'm unsure whether we should delete the assets from the stacks repository bucket, I can foresee a recover scenario where those objects could be useful.

**Comment by eamonnfaherty** [comment]
I cannot imagine deleting the assets in the bucket as that could break already deploy resources.  generally the solutions do not delete generated artefacts

**Comment by kunzt-aws** [comment]
I am experiencing the same issue. Resources are not removed when the status is set to false or terminated.
```
Schema: factory-2019-04-01
Stacks:
  - Name: "launchconstraint-role"
    Versions:
      - Name: "v2-0-0"
        Status: terminated
        Active: false
```
