### ISSUE TITLE
No possibility to delete portfolio from service catalog

### ISSUE THREAD

**Issue by kunzt-aws** [awslabs/aws-service-catalog-factory#267]
From testing I have no possibility to delete a portfolio based on the config file for the Service Catalog Factory.

Following code has no effect:
```
Schema: factory-2019-04-01  
Portfolios:
  - DisplayName: "1234567890"  
    Status: "terminated"
    Description: "Test Portfolio containing products"  
    ProviderName: "portfolio-engineering"
```
