### ISSUE TITLE
No capability to remove a product from a portfolio

### ISSUE THREAD

**Issue by kunzt-aws** [awslabs/aws-service-catalog-factory#268]
Today, products can only added to portfolios based on the config files.
To remove a products from a portfolio while not deleting the product from the Service Catalog, you need to manually remove the product using the AWS Console or the CLI.

Removing the product from the portfolio could be enabled in the configuration using the Status statement.

Example for configurations which are Portfolio-focused:
```
Schema: factory-2019-04-01  
Portfolios:
  - DisplayName: "Portfolio Name"  
    Description: "Portfolio Description"  
    ProviderName: "Portfolio ProviderName"
    Products:
      - Name: "Portfolio Product Name"  
        Owner: "Owner"
        Description: "Description"  
        Distributor: "Distributor"  
        SupportDescription: "SupportDescription"  
        SupportEmail: "SupportEmail"  
        SupportUrl: "SupportUrl" 
        Status: "Active/Inactive"
```

Example for configurations which are Product-focused:
```
Products:
  - Name: "Portfolio Product Name"  
    Owner: "Owner"
    Description: "Description"  
    Distributor: "Distributor"  
    SupportDescription: "SupportDescription"  
    SupportEmail: "SupportEmail"  
    SupportUrl: "SupportUrl" 
    Status: "Active/Inactive"
    Portfolios:
      - AssignedPortfolio
        Status: "Active/Inactive"
```
