### ISSUE TITLE
Enable override validate stack region

### ISSUE THREAD

**Issue by tbuatois** [awslabs/aws-service-catalog-factory#274]
Hello, 

I am trying to deploy a service catalog product from `eu-west-1` region but I am unable to pass Validate step in deployment pipeline. 
My stack reference a `AWS::CUR::ReportDefinition` resource which is only available on `us-east-1`.

I looking for  a way to defined that this particular product is validated on this specific region to pass test, or eventually skip test part. 

# Steps to reproduce

1. Create portfolio in region outside `us-east-1`
2. Add product to portfolio containing `AWS::CUR::ReportDefinition` resource 

# Actual results

`(ValidationError) when calling the ValidateTemplate operation: Template format error: Unrecognized resource types: [AWS::CUR::ReportDefinition]`

**Comment by eamonnfaherty** [comment]
have you tried using an AWS Cloudformation condition resource to check for the region us-east-1 ?

**Comment by tbuatois** [comment]
Yes there is a condition on the deployment, but validation failed anyway : 

```yml
...
Conditions:
  IsNorthVirginia:
    Fn::Equals:
      - Ref: AWS::Region
      - 'us-east-1'
Resources:
....
  LocalCur:
    Type: AWS::CUR::ReportDefinition
    Condition: IsNorthVirginia
    Properties:
      AdditionalArtifacts:
        - ATHENA
      AdditionalSchemaElements: 
        - RESOURCES
```

Validation of this template with the cli failed, unless --region us-east-1 is specified. But it can be successfully deployed on any region.
