### ISSUE TITLE
tag options support

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-factory#313]
I would like support for tag options

**Comment by eamonnfaherty** [comment]
support for the following three scenarios have been added:

```yaml
---
Schema: factory-2019-04-01

Portfolios:
  - DisplayName: "shared"
    Description: "Shared portfolio"
    ProviderName: "shared"
    TagOptions:
      - Key: "creating-team"
        Value: "ccoe"
    Products:
      - Name: vpc
        Owner: central-it@customer.com
        Distributor: central-it-team
        TagOptions:
          - Key: "product-type"
            Value: "networking"

Products:
  - Name: eks-cluster
    Owner: central-it@customer.com
    Distributor: central-it-team
    TagOptions:
      - Key: "creating-sub-team"
        Value: "networking-team"
    Portfolios:
      - shared
```

Some required fields have been omitted from the sample

this is in release: https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.94.0
