### ISSUE TITLE
IAM_PATTERN PrincipalType support

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-factory#328]
As a customer 
I would like to use IAM_PATTERN as a principal type 
so I can add principals more easily

**Comment by eamonnfaherty** [comment]
Support for this has been added but the feature will not work until CloudFormation support for IAM_PATTERN principal type goes live - the docs went live before the feature did.  I will add it to the docs once the feature goes live.

Here is a sample on how to use it.
```yaml
Portfolios:
  - PortfolioName: "XXX"
    Description: "YYY"
    ProviderName: "ZZZ"
    Associations:
      - PrincipalARN: arn:aws:iam:::role/Admin
        PrincipalType: IAM_PATTERN
```
