### ISSUE TITLE
Update Resource constraint

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-factory#331]
As a user 
I would like to use UpdateResource Constraints in factory
so I do not need to use puppet

Customer would like to use puppet import-portfolios or not use puppet at all.

**Comment by eamonnfaherty** [comment]
this is shipped:

```yaml
Portfolios:
  - PortfolioName: "XXX"
    Description: "YYY"
    ProviderName: "ZZZ"
    Constraints:
      ResourceUpdate:
        - Products: "VPC*"
          TagUpdateOnProvisionedProduct: NOT_ALLOWED
```

docs to follow later.
