### ISSUE TITLE
Setting Guidance has no affect

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-factory#332]
Setting the following guidance should be reflected in the provisioning artefact:

```yaml
      - Active: false
        Guidance: Deprecated
        Description: v1 of sleeper
        Name: v2
        Source:
          Configuration:
            BranchName: v2
            RepositoryName: sleeper
          Path: v2
          Provider: CodeCommit
```
