### ISSUE TITLE
Cannot Terminate a Service Catalog Product

### ISSUE THREAD

**Issue by mmarthab** [awslabs/aws-service-catalog-factory#354]
Please ensure you are using the latest version and have tried to run a validate command on your source files

We are creating a Service Catalog product using Service Catalog tools. The product gets created successfully but when terminating pipeline runs successfully but we cannot see the product get terminated. We tried to add Status terminated and even comment out the code for the product but still we cannot see the product get terminated. 

See code below:

```
Products:
  - Name: "aws-config-enable-config"
    Owner: "data-governance@example.com"
    Status: terminated
    Description: "Enables AWS Config"
    Distributor: "cloud-engineering"
    SupportDescription: "Speak to data-governance@example.com about exceptions and speak to cloud-engineering@example.com about implementation issues"
    SupportEmail: "cloud-engineering@example.com"
    SupportUrl: "https://wiki.example.com/cloud-engineering/governance/aws-config-enable-config"
    Tags:
      - Key: "type"
        Value: "governance"
      - Key: "creator"
        Value: "cloud-engineering"
      - Key: "cost-center"
        Value: "cloud-engineering"
    Versions:
      - Name: "v1"
        Description: "v1 of aws-config-enable-config"
        Active: False
        #Status: terminated
        Source:
          Provider: "CodeCommit"
          Configuration:
            RepositoryName: "aws-config-enable-config"
            BranchName: "main"
    Portfolios:
      - "cloud-engineering-governance"

```

We were only able to successfully 

1. Create product
2. Add Product Version
3. Disable Product Version. 
4. Terminate product version

# Expected results

The product gets terminated

# Actual results
product and version pipeline  does not get terminated
