### ISSUE TITLE
Terraform factory products not rendering pipeline jobs correctly

### ISSUE THREAD

**Issue by jagexjake** [awslabs/aws-service-catalog-factory#358]
# Steps to reproduce
0. Using scf version 0.102 and have https://github.com/awslabs/aws-service-catalog-products/tree/main/unsorted/aws-servicecatalog-factory-provisioners deployed
1. Using the following:
```
Portfolios:
  - DisplayName: foobar
    Components:
      - Name: backups-spoke
        Owner: ...
        Description: Configures AWS backups in the spoke acccounts
        Distributor: ...
        SupportDescription: ...
        SupportEmail: ...
        SupportUrl: ...
        PipelineMode: combined
        Tags:
          - Key: component-type
            Value: mandatory
          - Key: product-category
            Value: backups
        Versions:
          - Name: v1
            Description: Configures Terraform Backups
            Provisioner:
              Type: Terraform
              Version: 1.5.7
            Source:
              Provider: CodeStarSourceConnection
              Configuration:
                BranchName: main
                ConnectionArn: "{{resolve:ssm:github_connection}}"
                FullRepositoryId: org/repoa
                OutputArtifactFormat: "CODE_ZIP"
```
2. SCF pipeline runs cleanly, and creates pipeline and 3 codebuild steps
3.  ValidateProject fails, as the build specs are not being generated for Terraform and not using any of the jinja templating

# Expected results
Terraform would be supported

# Actual results
Terraform repos not being supported
