### ISSUE TITLE
Ability to define a product once for multiple protfolios

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-factory#54]
I'd like a product to be available in multiple portfolios.

At the moment I need to duplicate the entire product definition in each portfolio, which also duplicates pipelines and other supporting resources, as well as needing to change product definitions multiple times (once for each portfolio its defined in).

It would be good if we could define a product in a portfolio that refers to another product definition.

This could just be a way of pointing the product config in one portfolio to the definition in another, or to split out the definition of portfolios & products in the manifest.

E.g.

```yaml
portfolios:
  - DisplayName: portfolio-one
    Description: portfolio-one
  - DisplayName: portfolio-two
    Description: portfolio-two

products:
      - Name: my-product
        Owner: Test
        Description: This is my-product
        Distributor: Test
        SupportDescription: N/A
        SupportEmail: do-not-use@test.com
        SupportUrl: https://donotuse.com
        Tags:
          - Key: product-type
            Value: test
        Portfolios:
          - portfolio-one
          - portfolio-two
        Versions:
          - Name: develop
            Description: Development version. Do not use for Production!
            Source:
              Provider: CodeCommit
              Configuration:
                RepositoryName: my-product
                BranchName: develop
```

**Comment by eamonnfaherty** [comment]
Hey @jordan-evans 

Thanks for posting this request.  

Can I check why you wanted to have the same product in multiple portfolios?  Are you using servicecatalog-puppet with these products? Are you provisioning them via a launch or importing them into a local portfolio ?

**Comment by jordan-evans** [comment]
Hi @eamonnfaherty 

We use Puppet to deploy products into our Core Accounts (From Landing Zone), and to deploy a set of mandatory products into vended accounts. We also have a set of Optional products which we share into vended accounts via a local portfolio with a Launch Constraint.

In this particular scenario, we want to use Puppet to deploy one of the Optional Products into a Core Account. 

As Puppet can't deploy local products, we want to make these Optional Products available in 2 portfolios. One of them is a standard imported portfolio shared to Core Accounts whose products are deployed via Puppet. The other is a local portfolio shared to vended accounts that users elect to deploy that use a launch constraint.

Hope that explains things well enough!

Jordan

**Comment by eamonnfaherty** [comment]
Thanks for the extra info @jordan-evans .  I will have a think about this.  

At the moment I think the easiest change would be to allow puppet to provision local products within the account.

**Comment by jordan-evans** [comment]
Either works for me 😄

**Comment by jordan-evans** [comment]
I suppose with the local product provisioning the only thing that might need to bear in mind is that the local version of a portfolio / product should win over an imported one if they have the same name?

**Comment by eamonnfaherty** [comment]
I think this may be possible already.

If you add the PuppetRole to the spoke-local-portfolio when setting up your spoke:

```yaml
spoke-local-portfolios:
  account-vending-for-spokes:
    portfolio: demo-central-it-team-portfolio
    depends_on:
      - account-iam-for-spokes
      - account-vending-account-creation-shared
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/servicecatalog-puppet/PuppetRole
    constraints:
      launch:
        - products: 'account-vending-*'
          roles:
            - arn:aws:iam::${AWS::AccountId}:role/servicecatalog-puppet/PuppetRole
    deploy_to:
      tags:
        - tag: scope:spoke
          regions: default_region
```

You can then launch it using the regular launch setup but using your imported portfolio name in your manifest file - they must differ as for now the framework will check for imported portfolios first.

**Comment by eamonnfaherty** [comment]
I can look at adding a skip sharing configuration to launch schema as well as adding the puppet role to the associations and launch constraints automatically.

Please let me know how you get on.

**Comment by jordan-evans** [comment]
Thanks @eamonnfaherty, I'll have a play around with this now.

Adding the PuppetRole automatically as an association would be nice, but I'd also like the ability to tell Puppet whether it should look for an imported or local portfolio when carrying out a launch. Maybe this could just be a parameter on the launch configuration like below:

```yaml
  my_launch:
    portfolio: my-portfolio
    product: my-product
    portfolio_type: local | imported
    version: v1
    deploy_to:
      tags:
        - tag: ou:all-accounts
          regions: default_region
```

Will let you know how I get on with the local deployment.
